routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/home', 'PageController@getHome')->name('home');
Route::get('/', 'PageController@getIndex')->name('index');
Route::resource('/pages', 'PageController');
  Route::get('/posts','PostsController@index')->name('posts');
  Route::get('/posts/{post}/{slug}/','PostsController@show')->name('posts.show');
/**
 * These are admin routes
 *
 *
 */
Route::prefix('admin')->middleware('admin')-> group(function()
{
  Route::get('/', 'Backend\DashboardController@index')->name('admin.dashboard');
  Route::resource('users', 'Backend\UserManagementController');
  Route::post('/users/upload', 'Backend\UserManagementController@postUpload')->name('avatar-upload');
  Route::post('/users/upload/delete', 'Backend\UserManagementController@deleteUpload')->name('delete-upload');
  Route::resource('menus', 'Backend\MenusController');
  Route::resource('pages', 'Backend\PagesController');
  Route::post('menus/order', 'Backend\MenusController@order')->name('order.menu');
  Route::resource('slides', 'Backend\SlidesController');
  Route::resource('categories', 'Backend\CategoriesController');
  Route::resource('posts', 'Backend\PostsController');
  Route::get('setting/headerfooter','Backend\SettingController@headerFooterEdit')->name('HFE');
  Route::PATCH('setting/headerfooter','Backend\SettingController@headerFooterUpdate')->name('HFU');
  Route::get('setting/logo','Backend\SettingController@logoEdit')->name('logo-edit');
  Route::PATCH('setting/logo','Backend\SettingController@logoUpdate')->name('logo-update');
});

app/Models/Slide.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slide extends Model
{
	protected $table = 'slides';
	protected $fillable = ['title','image','is_visible','page_id','style','script','content'];
	protected $attributes = array(
	'page_id' => '0',
	'is_visible' => 'boolean',

);

public function page()
{
    return $this->belongsTo('App\Models\Page');
}


}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Repositories\Categories;
use App\Models\Category;
use App\Http\Requests\CategoryRequest;
use Auth;
use Session;

class CategoriesController extends MainController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     private $view = 'backend.categories';
     public function __construct(Categories $categories)
     {
         $this->categories = $categories;
    }
    public function index()
    {
      $items = $this->categories->all();
      return view($this->view.'.'.__FUNCTION__,compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $items = $this->categories->all();
        return view($this->view.'.'.__FUNCTION__,compact('items'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
      $category = Category::create($request->except('user_id'));
      $category->user_id = Auth::user()->id;
      $category->save();
      Session::flash('success', 'Create category was successfully save!');
      return redirect()->route('categories.index');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $category = $this->categories->findCategory($id);
      return view($this->view.'.'.__FUNCTION__, compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
      $category = $this->categories->findCategory($id);
      $category->name = $request->name;
      $category->user_id = Auth::user()->id;
      $category->save();
      Session::flash('success', 'Update category was successfully save!');
      return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->categories->findCategory($id);
        $category->delete();
        Session::flash('success', 'Destroy user was successfully save!');
        return back();
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

class DashboardController extends MainController
{

    public function index()
    {
      return view ('backend.dashboard.index');
    }

}

app/Http/Controllers/Backend/MainController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MainController extends Controller
{
    
}

app/Http/Controllers/Backend/MenusController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Repositories\Menus;
use App\Models\Menu;
use App\Http\Requests\MenuRequest;
use Hash;
use Auth;
use Session;
use Image;
use File;

class MenusController extends MainController
{

    private $view = 'backend.menus';


    public function __construct(Menus $menus)
    {
          $this->menus = $menus;

    }

    public function index()
    {
        $itemTreeView = $this->menus->allTreeView();
        $items = $this->menus->all();
        return view($this->view.'.'.__FUNCTION__, compact('items','itemTreeView'));

    }

    public function create()
    {

      $list_main_menu = $this->menus->listMenu();



      return view($this->view.'.'.__FUNCTION__, compact('list_main_menu'));


    }

    public function store(MenuRequest $request)
    {


      //dd($request);
      $menu = Menu::create($request->except('user_id'));
      $menu->user_id = Auth::user()->id;

      $menu->save();
      Session::flash('success', 'Create menus was successfully save!');
      return redirect()->route('menus.index');

    }

    public function edit($id)
    {
      $list_main_menu = $this->menus->listMenu();

      $menu = $this->menus->findMenu($id);

      return view($this->view.'.'.__FUNCTION__, compact('menu', 'list_main_menu'));
    }

    public function update(MenuRequest $request, $id)
    {

        $menu = $this->menus->findMenu($id);
        $menu->title = $request->title;
        $menu->path = $request->path;
        $menu->script = $request->script;
        $menu->parent_id = $request->parent_id;
        $menu->save();
        Session::flash('success', 'Update menus was successfully save!');
        return redirect()->route('menus.index');

    }

    public function destroy($id)
    {
      $menu = $this->menus->findMenu($id);

      $menu->delete();
      Session::flash('success', 'Destroy user was successfully save!');
      return back();
    }

    public function order(Request $request)
    {
      if($request->ajax()){

        $list = $request->list;

        $output = array();
        $list = parse_str($list, $output);

        $i = 0;

        foreach ($output['list'] as $key => $value)
        {

          Menu::where('id', $value)->update(['order' => $i]);
          $i++;
        }


      }
    }
  }

app/Http/Controllers/Backend/PagesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Repositories\Pages;
use App\Models\Page;
use App\Http\Requests\PageRequest;
use Hash;
use Auth;
use Session;
use Image;
use File;

class PagesController extends MainController
{

    private $view = 'backend.pages';


    public function __construct(Pages $pages)
    {
        $this->pages = $pages;
    }


    public function index()
    {

        $items = $this->pages->all();
        return view($this->view.'.'.__FUNCTION__,compact('items'));

    }

    public function create()
    {

        return view($this->view.'.'.__FUNCTION__);

    }

    public function store(PageRequest $request)
    {
      $page = Page::create($request->except('user_id'));
      $page->user_id = Auth::user()->id;
      $page->save();
      Session::flash('success', 'Create pages was successfully save!');
      return redirect()->route('pages.index');
    }

    public function edit($id)
    {

      $page = $this->pages->findPage($id);

      return view($this->view.'.'.__FUNCTION__, compact('page'));
    }

    public function update(PageRequest $request, $id)
    {
        $page = $this->pages->findPage($id);
        $page->title = $request->title;
        $page->content = $request->content;
        $page->tags = $request->tags;
        $page->style = $request->style;
        $page->script = $request->script;
        $page->slug = $request->slug;
        $page->save();
        Session::flash('success', 'Update user was successfully save!');
        return redirect()->route('pages.index');
    }

    public function destroy($id)
    {
        $page = $this->pages->findPage($id);
        $page->delete();
        Session::flash('success', 'Destroy user was successfully save!');
        return back();
    }


  }

app/Http/Controllers/Backend/PostsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Repositories\Posts;
use App\Models\Post;
use App\Http\Requests\PostRequest;
use Auth;
use Session;
use Image;
use File;

class PostsController extends MainController
{

    private $view = 'backend.posts';


    public function __construct(Posts $posts)
    {
        $this->posts = $posts;
    }


    public function index()
    {

        $items = $this->posts->all();
        return view($this->view.'.'.__FUNCTION__,compact('items'));

    }

    public function create()
    {
        $categories = $this->posts->getCategories();

        return view($this->view.'.'.__FUNCTION__,compact('categories'));

    }
    public function store(PostRequest $request)
    {

      $post = Post::create($request->except(['user_id','category_id','cover']));
      $post->user_id = Auth::user()->id;
      if($request->has('category_id'))
      {

        foreach ($request->category_id as $category_id)
        {
				      $post->categories()->attach($category_id);
			  }

      }
      if($request->hasFile('cover'))
      {
        $image = $request->file('cover');
        $image_name = $image->getClientOriginalName();
        $location = public_path('uploads/postImages/' . $image_name);
        Image::make($image)->save($location);
        $post->cover = $image_name;
      }


      $post->save();
      Session::flash('success', 'Create pages was successfully save!');
      return redirect()->route('posts.index');
    }
    public function edit($id)
    {
      $post = $this->posts->findPost($id);
      $edit_categories = $this->posts->getCategoriesFormRelation($id);
      $categories = $this->posts->getCategories();
      return view($this->view.'.'.__FUNCTION__, compact('post','categories','edit_categories'));
    }

    public function update(PostRequest $request, $id)
    {
        $post = $this->posts->findPost($id);
        if($request->has('category_id'))
        {
          $post->categories()->detach();
          foreach ($request->category_id as $category_id)
          {
            $post->categories()->attach($category_id);
          }
        }
        if($request->hasFile('cover'))
        {
          $path = 'uploads/postImages/';
          File::delete($path.$post->cover);

          $image = $request->file('cover');
          $image_name = $image->getClientOriginalName();
          $location = public_path($path.$image_name);
          Image::make($image)->save($location);
          $post->cover = $image_name;
        }
        $post->title = $request->title;
        $post->is_visible = $request->is_visible;
        $post->content = $request->content;
        $post->tags = $request->tags;
        $post->summary = $request->summary;
        $post->slug = $request->slug;
        $post->save();
        Session::flash('success', 'Update user was successfully save!');
        return redirect()->route('posts.index');
    }

    public function destroy($id)
    {
        $path = 'uploads/postImages/';
        $post = $this->posts->findPost($id);
        File::delete($path.$post->cover);
        $post->categories()->detach();
        $post->delete();
        Session::flash('success', 'Destroy post was successfully save!');
        return back();
    }




  }

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Repositories\Setting;

use App\Http\Requests\{HeaderFooterRequest, LogoRequest};
use Hash;
use Auth;
use Session;
use Image;
use File;

class SettingController extends MainController
{

    private $view = 'backend.setting';


    public function __construct(Setting $setting)
    {

        $this->setting = $setting;

    }

    public function headerFooterEdit()
    {
      $get = $this->setting->getHeaderFooter(1);
      return view($this->view.'.'.__FUNCTION__, compact('get'));
    }

    public function headerFooterUpdate(HeaderFooterRequest $request)
    {

      $hf = $this->setting->getHeaderFooter(1);
      $hf->header = $request->header;
      $hf->footer = $request->footer;
      $hf->script = $request->script;
      $hf->style = $request->style;
      $hf->user_id = Auth::user()->id;
      $hf->save();

    Session::flash('success', 'Update Header And Footer was successfully save!');
    return redirect()->back();
  }
  public function logoEdit()
  {
      $get = $this->setting->getLogo(1);
      return view($this->view.'.'.__FUNCTION__,compact('get'));
  }
  public function logoUpdate(LogoRequest $request)
  {
      $logo = $this->setting->getLogo(1);
      if($request->hasFile('image'))
      {
        $path = 'uploads/logo/';
        File::delete($path.$logo->image);
        $image = $request->file('image');
        $image_name = $image->getClientOriginalName();
        $location = public_path($path.$image_name);
        Image::make($image)->save($location);
        $logo->image = $image_name;
      }
      $logo->save();
      Session::flash('success', 'Update Logo was successfully save!');
      return redirect()->back();
  }

}

app/Http/Controllers/Backend/SlidesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Repositories\Slides;
use App\Models\Slide;
use App\Http\Requests\SlideRequest;
use Hash;
use Auth;
use Session;
use Image;
use File;
use Illuminate\Support\Facades\Input;
use Validator;

class SlidesController extends MainController
{
    private $view = 'backend.slides';


    public function __construct(Slides $slides)
    {
        $this->slide = $slides;
    }


    public function index()
    {
        $items = $this->slide->all();
        return view($this->view.'.'.__FUNCTION__,compact('items'));
    }

    public function create()
    {
        $list_page = $this->slide->PageList();
        return view($this->view.'.'.__FUNCTION__, compact('list_page'));
    }

    public function store(SlideRequest $request)
    {

        $slide = Slide::create($request->except(['file']));
        $images = $request->file('file');
        $img_array=array();
        foreach ($images as $image) {
            $image_name = $image->getClientOriginalName();
            $location = public_path('uploads/slideImages/' . $image_name);
            Image::make($image)->save($location);
            $img_array[]=$image_name;
        }
      $slide->image =  implode("|", $img_array);
      $slide->save();
    }

    public function edit($id)
    {
        $list_page = $this->slide->PageList();
        $items = $this->slide->findSlide($id);
        return view($this->view.'.'.__FUNCTION__, compact('items','list_page'));
    }
    public function destroy($id)
    {
        $slide = $this->slide->findSlide($id);
        foreach(explode('|', $slide->image) as $filename)
        {
          $path = 'uploads/slideImages/';
          File::delete($path.$filename);
        }
        $slide->delete();
        Session::flash('success', 'Destroy user was successfully save!');
        return back();
    }

}

resources/views/backend/slides/create.blade.php
@extends('layouts.backend')
@section('content')
<h1 class="page-header">Create User

</h1>




{!! Form::model($slide = new App\Models\Slide, ['route' => ['slides.store' ,'id' => 'form-dropzone'], 'files' => true ]) !!}
@include('backend.slides.form', ['submit_text' => ('Save')])
{!! Form::close() !!}



<script>

$("div#dropzone").dropzone({
  url: "{{route('slides.store')}}",
  headers:{  'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
  autoProcessQueue: false,
  uploadMultiple: true,
  parallelUploads: 100,
  maxFiles: 100,
  addRemoveLinks: true,

  init: function() {

    var $this = this;
    $("input[type=submit").click(function(e) {
      e.preventDefault();
      e.stopPropagation();


      if($this.files.length > 0)
      {

        $this.processQueue();
      }
      else
      {
        $( "#form-dropzone" ).submit();
      }

    });
    this.on("sendingmultiple", function(file, xhr, formData) {

       formData.append("title", $('#title').val());
       formData.append("content", $('#content').val());
       formData.append("script", $('#script').val());
       formData.append("style", $('#style').val());
       formData.append("page_id", $("#menu").val());
       formData.append("is_visible", $("#is_visible").is(':checked') ? 1 : 0);

    });

    this.on("successmultiple", function(files, response) {

      location = '{{{ action('Backend\SlidesController@index') }}}';
    });
  },

});
Dropzone.autoDiscover = false;

</script>
@endsection

resources/views/backend/slides/edit.blade.php
@extends('layouts.backend')
@section('content')
<h1 class="page-header">Edit Page</h1>

{!! Form::model($items, ['route' => ['slides.update',$items->id], 'method' => 'PATCH']) !!}
  @include('backend.slides.form', ['submit_text' => ('Save')])
{!! Form::close() !!}

<script type="text/javascript">
$("div#dropzone").dropzone({
}
});


</script>
@endsection

resources/views/backend/slides/form.blade.php
<div class="row">
  <div class="col-md-6">
      <div class="form-group">
        <label>Title</label> {!! Form::text('title', null, ['class' => 'form-control','id'=>'title']) !!}
      </div>
</div>
  <div class="col-md-4">
      <div class="form-group">
        <label>Menu</label> {!! Form::select('page_id', $list_page, null, ['class' => 'form-control','id'=>'menu']) !!}
      </div>
</div>
<div class="col-md-2">
  <div class="form-group">
    <label>Visible</label>
    <input checked="checked" name="is_visible" type="checkbox" value="1" id="is_visible">
  </div>
</div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="dropzone" id="dropzone" name="mainFileUploader" >
    </div>
  </div>
</row>

<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <label>Content</label> {!! Form::textarea('content', null, ['class' => 'form-control body-page','id'=>'content']) !!}
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <label>Script</label>  {!! Form::textarea('script', null, ['class' => 'form-control','id'=>'script']) !!}
    </div>
  </div>
  <div class="col-md-6">
      <div class="form-group">
        <label>Style</label> {!! Form::textarea('style', null, ['class' => 'form-control','id'=>'style']) !!}
      </div>
  </div>
</div>
<div class="row">
    <div class="col-md-12">
  <div class="form-group">
    {!! Form::submit($submit_text, ['class' => 'btn btn-success submit-form', 'style' => 'width:100%']) !!}
  </div>
</div>
</div>

<script type="text/javascript">



</script>

resources/views/backend/slides/index.blade.php
@extends('layouts.backend')

@section('content')

@include('layouts.partial_page.model_delete')

<h1 class="page-header">Slides Image
  <div class="pull-right">
    <a href="{!! url('admin/slides/create') !!}"><button type="button" class="btn btn-success">NEW</button></a>
  </div>
</h1>
<table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th></th>
         <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach($items as $i)
      <tr>
        <td>{{ $i->title }}</td>
        <td>
            <a href="{{ route('slides.edit', $i->id) }}"><button type="button" class="btn btn-primary btn-xs"><i class="fa fa-edit"></i></button></a>
        </td>
        <td>
          {{ Form::open(['method' => 'DELETE', 'route' => ['slides.destroy', $i->id], 'class' => 'form-delete']) }}
            {{ Form::button('<i class="fa fa-trash"></i>', ['class' => 'btn btn-danger btn-xs delete ', 'name' => 'delete_modal']) }}
          {{ Form::close() }}
        </td>
      </tr>

      @endforeach

    </tbody>
  </table>

@endsection